name: UniMRCP-MS-Docker-CI

on:
  push:
    paths:
      - '.github/workflows/UniMRCP-MS-Docker.yml'
  schedule:
    - cron: '0 0 * * 6'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_USERNAME: drhippo
  DOCKER_NAME: drhippo/unimrcp_ms

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      name: Checkout Azure-Samples/Cognitive-Speech-TTS
      with:
        repository: Azure-Samples/Cognitive-Speech-TTS
        path: Cognitive-Speech-TTS
    - name: Log CPU info
      run: cat /proc/cpuinfo
    - name: Patch docker file
      run: |
        sed -i 's/unimrcp:latest/drhippo\/unimrcp:latest-devel/' Cognitive-Speech-TTS/MRCP/docker/ms-plugins/Dockerfile
    - name: Get docker tag
      run: |
        # get speech sdk version
        sdk_version=$(curl https://aka.ms/csspeech/linuxbinary -i | grep Location | sed 's/^.*Linux-\(.*\)\.tar.*$/\1/g')
        echo "docker_tag=unimrcp1.6.0-sdk$sdk_version" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: Cognitive-Speech-TTS/MRCP/
        file: Cognitive-Speech-TTS/MRCP/docker/ms-plugins/Dockerfile
        tags: |
          ${{ env.DOCKER_NAME }}:latest
          ${{ env.DOCKER_NAME }}:${{ env.docker_tag }}
        push: ${{ github.ref == 'refs/heads/master' }}
