name: UniMRCP-MS-Docker-CI

on:
  push:
    paths: 
      - '.github/workflows/UniMRCP-MS-Docker.yml'
  schedule:
    - cron: '0 0 * * 6'
      
env:
  DOCKER_USERNAME: drhippo
  DOCKER_NAME: drhippo/unimrcp_ms

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout Cognitive-Speech-TTS.git
      run: |
        git clone https://github.com/Azure-Samples/Cognitive-Speech-TTS.git
    - name: Patch docker file
      run: |
        sed -i 's/unimrcp:latest/drhippo\/unimrcp:latest-devel/' Cognitive-Speech-TTS/MRCP/docker/ms-plugins/Dockerfile 
    - name: Build docker
      run: |
        cd Cognitive-Speech-TTS/MRCP
        docker build --no-cache -t ${{ env.DOCKER_NAME }} -f ./docker/ms-plugins/Dockerfile .
        # get speech sdk version
        sdk_version=$(curl https://aka.ms/csspeech/linuxbinary -i | grep Location | sed 's/^.*Linux-\(.*\)\.tar.*$/\1/g')
        docker_tag=unimrcp1.6.0-sdk$sdk_version
        docker tag ${{ env.DOCKER_NAME }}:latest ${{ env.DOCKER_NAME }}:$docker_tag
        echo "::set-env name=docker_tag::$docker_tag"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ env.DOCKER_NAME }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.docker_tag }}"
